name: Reanalyse published data
description: Provide parameters for reanalysis of published data
title: Reanalyse published data
labels: ['reanalysis']
assignees: ['']

body:
  - type: input
    id: doi
    attributes:
      label: DOI
      placeholder: e.g., 10.1234/example
    validations:
      required: true

  - type: input
    id: analysis_title
    attributes:
      label: Analysis title
      placeholder: Enter the title of the analysis
    validations:
      required: true

  - type: dropdown
    id: udg_treatment
    attributes:
      label: UDG treatment
      description: The UDG treatment applied to the library preparations
      options:
        - unknown
        - full
        - half
        - untreated
    validations:
      required: true

  - type: dropdown
    id: strandedness
    attributes:
      label: Strandedness
      description: The strandedness of the library preparations
      options:
        - unknown
        - double
        - single
    validations:
      required: true

  - type: textarea
    id: user_provided_notes
    attributes:
      label: Notes
      placeholder: Enter any additional notes or context
      description: Free text field for user-supplied notes (supports markdown)

